name: Build

on:
  push:
    branches:
      - main

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_setup
        uses: asdf-vm/actions/setup@v2
      - name: asdf_plugin_test
        run: |
          asdf plugin add texlive https://github.com/javiergarea/asdf-texlive.git
          asdf list-all texlive
          asdf install texlive latest
          asdf global texlive latest
          tex --version || fail "Installation failed"
